In [1]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
import os
import numpy as np
import yfinance as yf

In [2]:
def fetch_info():
    try:
        url = f"https://en.wikipedia.org/wiki/List_of_Dow_Jones_Industrial_Average_companies"
        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36,accept-language=en-US,en;q=0.9,accept:application/json"
        }
        # send get request to the Wikipedia page
        response = requests.get(url, headers=headers)
        soup = BeautifulSoup(response.content, "html.parser")
        # get symbols of Dow Jones components
        tables = soup.find_all("table")
        # convert table to DataFrame
        df = pd.read_html(str(tables))[0]
        # clean up
        df.drop(columns=['Notes'], inplace=True)
        return df

    except Exception as e:
        print(
            f"Error fetching info for Dow Jones Industrial Average from WIKI: {e}")
        return None

In [3]:
djia_components = fetch_info()
print(djia_components)
tickers = djia_components['Symbol'].tolist()
print(tickers)

                   Company Exchange Symbol                  Sector  Date added
0                       3M     NYSE    MMM             Industrials  1976-08-09
1       Alphabet (Class A)   NASDAQ  GOOGL  Communication Services  2026-06-29
2         American Express     NYSE    AXP              Financials  1982-08-30
3                    Amgen   NASDAQ   AMGN             Health Care  2020-08-31
4                   Amazon   NASDAQ   AMZN  Consumer Discretionary  2024-02-26
5                    Apple   NASDAQ   AAPL  Information Technology  2015-03-19
6                   Boeing     NYSE     BA             Industrials  1987-03-12
7              Caterpillar     NYSE    CAT             Industrials  1991-05-06
8                  Chevron     NYSE    CVX                  Energy  2008-02-19
9                    Cisco   NASDAQ   CSCO  Information Technology  2009-06-08
10               Coca-Cola     NYSE     KO        Consumer Staples  1987-03-12
11                  Disney     NYSE    DIS  Communication Services  1991-05-06
12           Goldman Sachs     NYSE     GS              Financials  2013-09-23
13              Home Depot     NYSE     HD  Consumer Discretionary  1999-11-01
14  Honeywell Technologies   NASDAQ    HON             Industrials  2020-08-31
15                     IBM     NYSE    IBM  Information Technology  1979-06-29
16       Johnson & Johnson     NYSE    JNJ             Health Care  1997-03-17
17          JPMorgan Chase     NYSE    JPM              Financials  1991-05-06
18              McDonald's     NYSE    MCD  Consumer Discretionary  1985-10-30
19                   Merck     NYSE    MRK             Health Care  1979-06-29
20               Microsoft   NASDAQ   MSFT  Information Technology  1999-11-01
21                    Nike     NYSE    NKE  Consumer Discretionary  2013-09-23
22                  Nvidia   NASDAQ   NVDA  Information Technology  2024-11-08
23        Procter & Gamble     NYSE     PG        Consumer Staples  1932-05-26
24              Salesforce     NYSE    CRM  Information Technology  2020-08-31
25        Sherwin-Williams     NYSE    SHW               Materials  2024-11-08
26               Travelers     NYSE    TRV              Financials  2009-06-08
27      UnitedHealth Group     NYSE    UNH             Health Care  2012-09-24
28                    Visa     NYSE      V              Financials  2013-09-23
29                 Walmart   NASDAQ    WMT        Consumer Staples  1997-03-17
['MMM', 'GOOGL', 'AXP', 'AMGN', 'AMZN', 'AAPL', 'BA', 'CAT', 'CVX', 'CSCO', 'KO', 'DIS', 'GS', 'HD', 'HON', 'IBM', 'JNJ', 'JPM', 'MCD', 'MRK', 'MSFT', 'NKE', 'NVDA', 'PG', 'CRM', 'SHW', 'TRV', 'UNH', 'V', 'WMT']

/var/folders/j6/2sp53bgs4612lcxv_stnsxk00000gn/T/ipykernel_60630/672945357.py:13: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[0]

In [4]:
# fetch historical data for the tickers
start_date = "2025-01-01"
end_date = "2025-12-31"
historical_data = yf.download(
    tickers, start=start_date, end=end_date, multi_level_index=False)
historical_data = historical_data['Close']
print(historical_data)

[*********************100%***********************]  30 of 30 completed

Ticker            AAPL        AMGN        AMZN         AXP          BA  \
Date
2025-01-02  242.093124  246.071320  220.220001  292.864929  171.869995
2025-01-03  241.606674  247.912506  224.190002  298.127502  169.899994
2025-01-06  243.234833  245.416458  227.610001  296.947174  170.779999
2025-01-07  240.464951  248.709702  222.110001  297.084869  172.509995
2025-01-08  240.951385  250.750137  222.130005  297.901276  171.759995
...                ...         ...         ...         ...         ...
2025-12-23  271.620667  324.843079  232.139999  379.103363  216.850006
2025-12-24  273.066742  327.263550  232.380005  380.015930  218.160004
2025-12-26  272.657806  326.254181  232.520004  377.972565  216.440002
2025-12-29  273.016876  323.020416  232.070007  372.288818  217.250000
2025-12-30  272.338684  322.099213  232.529999  370.374451  218.500000

Ticker             CAT         CRM       CSCO         CVX         DIS  ...  \
Date                                                                   ...
2025-01-02  352.265259  326.278229  56.567005  136.401367  108.774353  ...
2025-01-03  356.201355  328.488434  56.721184  137.461258  109.108086  ...
2025-01-06  356.602844  326.149841  56.634460  136.912689  109.000114  ...
2025-01-07  355.427856  320.624115  56.788647  139.079010  109.333832  ...
2025-01-08  353.538116  322.567963  57.048836  139.739120  107.733925  ...
...                ...         ...        ...         ...         ...  ...
2025-12-23  578.882446  261.636047  76.601837  146.421265  112.359055  ...
2025-12-24  580.214355  263.453613  76.601837  146.411560  113.609474  ...
2025-12-26  579.458923  264.267975  76.739304  145.944580  112.696465  ...
2025-12-29  575.095642  264.416992  76.376030  146.888229  113.321678  ...
2025-12-30  573.883057  264.109100  76.002937  148.172363  113.917114  ...

Ticker             MRK        MSFT        NKE        NVDA          PG  \
Date
2025-01-02   93.644005  412.895355  70.126442  137.949387  158.186722
2025-01-03   93.615677  417.600555  69.783760  144.093307  157.376633
2025-01-06   94.163353  422.039459  68.536774  149.040375  153.059357
2025-01-07   95.390915  416.633850  68.622452  139.774597  153.726471
2025-01-08   94.286110  418.794159  67.860939  139.744690  154.488876
...                ...         ...        ...         ...         ...
2025-12-23  102.915771  483.780792  55.864128  188.768295  140.062454
2025-12-24  104.297249  484.943390  58.455662  188.169678  141.343964
2025-12-26  104.620575  484.635345  59.361725  190.085205  141.588501
2025-12-29  104.463821  484.029236  59.634521  187.780594  141.422195
2025-12-30  103.915138  484.406860  59.615032  187.102173  140.913513

Ticker             SHW         TRV         UNH           V         WMT
Date
2025-01-02  327.879883  234.380066  482.838013  310.319244   88.582581
2025-01-03  331.206268  235.742218  490.963287  310.822662   89.350296
2025-01-06  332.465973  235.343307  491.604523  308.976898   89.990067
2025-01-07  329.100159  235.148712  492.159546  307.624664   89.379814
2025-01-08  332.190460  236.209259  501.988464  308.542633   90.354233
...                ...         ...         ...         ...         ...
2025-12-23  321.755127  289.196991  318.502838  351.270630  110.198242
2025-12-24  323.045929  290.561615  321.228943  353.020142  110.903748
2025-12-26  323.135345  288.860809  325.396545  352.881012  111.032928
2025-12-29  322.926819  288.672913  322.562592  352.493286  111.817932
2025-12-30  323.850220  289.117889  325.720184  351.509186  111.211784

[249 rows x 30 columns]

In [5]:
monthly_returns = historical_data.resample('M').ffill().pct_change()
print(monthly_returns)

Ticker          AAPL      AMGN      AMZN       AXP        BA       CAT  \
Date
2025-01-31       NaN       NaN       NaN       NaN       NaN       NaN
2025-02-28  0.025873  0.088042 -0.106866 -0.051945 -0.010707 -0.074009
2025-03-31 -0.081500  0.011329 -0.103731 -0.106027 -0.023364 -0.041140
2025-04-30 -0.043353 -0.066217 -0.030695 -0.006525  0.074406 -0.057735
2025-05-31 -0.053584 -0.000664  0.111647  0.103750  0.131412  0.125328
2025-06-30  0.021509 -0.031126  0.070143  0.084782  0.010660  0.115450
2025-07-31  0.011698  0.056910  0.067095 -0.059296  0.058751  0.132440
2025-08-31  0.119639 -0.017133 -0.021827  0.106812  0.057880 -0.043331
2025-09-30  0.096881 -0.019151 -0.041179  0.002656 -0.080322  0.138674
2025-10-31  0.061815  0.057512  0.112265  0.088765 -0.068619  0.213284
2025-11-30  0.032364  0.165848 -0.045041  0.012585 -0.059795 -0.002599
2025-12-31 -0.020692 -0.048544 -0.002959  0.022230  0.156085  0.002831

Ticker           CRM      CSCO       CVX       DIS  ...       MRK      MSFT  \
Date                                                ...
2025-01-31       NaN       NaN       NaN       NaN  ...       NaN       NaN
2025-02-28 -0.128329  0.057921  0.075001  0.006545  ... -0.066484 -0.041618
2025-03-31 -0.099010 -0.037436  0.054659 -0.132689  ... -0.018586 -0.054409
2025-04-30  0.002877 -0.058249 -0.186682 -0.078521  ... -0.050802  0.052932
2025-05-31 -0.012430  0.091980  0.016942  0.242881  ... -0.098122  0.166840
2025-06-30  0.029214  0.100571  0.047476  0.101724  ...  0.040507  0.080481
2025-07-31 -0.052660 -0.012837  0.059013 -0.039513  ... -0.013138  0.072556
2025-08-31 -0.008052  0.014835  0.070877 -0.006129  ...  0.076805 -0.048692
2025-09-30 -0.073511 -0.009697 -0.033064 -0.032776  ...  0.007597  0.022223
2025-10-31  0.098776  0.074999  0.015648 -0.016419  ...  0.024425 -0.000270
2025-11-30 -0.114704  0.052387 -0.031081 -0.072367  ...  0.219237 -0.048047
2025-12-31  0.155328  0.006109  0.007808  0.106219  ...  0.020381 -0.009207

Ticker           NKE      NVDA        PG       SHW       TRV       UNH  \
Date
2025-01-31       NaN       NaN       NaN       NaN       NaN       NaN
2025-02-28  0.032900  0.040393  0.047292  0.011475  0.054287 -0.124481
2025-03-31 -0.196761 -0.132325 -0.019673 -0.033999  0.027281  0.107437
2025-04-30 -0.111531  0.004982 -0.040116  0.010682 -0.001248 -0.214434
2025-05-31  0.074291  0.240636  0.045027  0.018916  0.043804 -0.266211
2025-06-30  0.180263  0.169252 -0.062217 -0.043059 -0.025595  0.040656
2025-07-31  0.051379  0.125831 -0.049090 -0.036347 -0.027286 -0.200051
2025-08-31  0.035882 -0.020746  0.043663  0.108022  0.043306  0.241665
2025-09-30 -0.094063  0.071251 -0.021587 -0.053495  0.032549  0.121369
2025-10-31 -0.073713  0.085272 -0.014504 -0.003812 -0.037963 -0.010831
2025-11-30  0.000619 -0.125883 -0.014697 -0.001295  0.090239 -0.034518
2025-12-31 -0.047182  0.059607 -0.027740 -0.051005  0.002311  0.014020

Ticker             V       WMT
Date
2025-01-31       NaN       NaN
2025-02-28  0.062962  0.004584
2025-03-31 -0.033774 -0.107280
2025-04-30 -0.014153  0.107757
2025-05-31  0.058745  0.017570
2025-06-30 -0.027766 -0.009522
2025-07-31 -0.026982  0.002045
2025-08-31  0.020057 -0.007894
2025-09-30 -0.029564  0.062693
2025-10-31 -0.001875 -0.018242
2025-11-30 -0.016545  0.092212
2025-12-31  0.057349  0.014823

[12 rows x 30 columns]

/var/folders/j6/2sp53bgs4612lcxv_stnsxk00000gn/T/ipykernel_60630/1568143435.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly_returns = historical_data.resample('M').ffill().pct_change()

In [ ]:
#see the difference between simple monthly returns and compounded monthly returns
mth_return_df = historical_data.pct_change().resample('M').agg(lambda x: (1 + x).prod() - 1)
print(mth_return_df)

Ticker          AAPL      AMGN      AMZN       AXP        BA       CAT  \
Date
2025-01-31 -0.032192  0.100818  0.079284  0.066235  0.027055  0.036222
2025-02-28  0.025873  0.088042 -0.106866 -0.051945 -0.010707 -0.074009
2025-03-31 -0.081500  0.011329 -0.103731 -0.106027 -0.023364 -0.041140
2025-04-30 -0.043353 -0.066217 -0.030695 -0.006525  0.074406 -0.057735
2025-05-31 -0.053584 -0.000664  0.111647  0.103750  0.131412  0.125328
2025-06-30  0.021509 -0.031126  0.070143  0.084782  0.010660  0.115450
2025-07-31  0.011698  0.056910  0.067095 -0.059296  0.058751  0.132440
2025-08-31  0.119639 -0.017133 -0.021827  0.106812  0.057880 -0.043331
2025-09-30  0.096881 -0.019151 -0.041179  0.002656 -0.080322  0.138674
2025-10-31  0.061815  0.057512  0.112265  0.088765 -0.068619  0.213284
2025-11-30  0.032364  0.165848 -0.045041  0.012585 -0.059795 -0.002599
2025-12-31 -0.020692 -0.048544 -0.002959  0.022230  0.156085  0.002831

Ticker           CRM      CSCO       CVX       DIS  ...       MRK      MSFT  \
Date                                                ...
2025-01-31  0.033388  0.032368  0.016904  0.020213  ... -0.003529 -0.008409
2025-02-28 -0.128329  0.057921  0.075001  0.006545  ... -0.066484 -0.041618
2025-03-31 -0.099010 -0.037436  0.054659 -0.132689  ... -0.018586 -0.054409
2025-04-30  0.002877 -0.058249 -0.186682 -0.078521  ... -0.050802  0.052932
2025-05-31 -0.012430  0.091980  0.016942  0.242881  ... -0.098122  0.166840
2025-06-30  0.029214  0.100571  0.047476  0.101724  ...  0.040507  0.080481
2025-07-31 -0.052660 -0.012837  0.059013 -0.039513  ... -0.013138  0.072556
2025-08-31 -0.008052  0.014835  0.070877 -0.006129  ...  0.076805 -0.048692
2025-09-30 -0.073511 -0.009697 -0.033064 -0.032776  ...  0.007597  0.022223
2025-10-31  0.098776  0.074999  0.015648 -0.016419  ...  0.024425 -0.000270
2025-11-30 -0.114704  0.052387 -0.031081 -0.072367  ...  0.219237 -0.048047
2025-12-31  0.155328  0.006109  0.007808  0.106219  ...  0.020381 -0.009207

Ticker           NKE      NVDA        PG       SHW       TRV       UNH  \
Date
2025-01-31  0.043844 -0.131878  0.006158  0.075039  0.017809  0.075281
2025-02-28  0.032900  0.040393  0.047292  0.011475  0.054287 -0.124481
2025-03-31 -0.196761 -0.132325 -0.019673 -0.033999  0.027281  0.107437
2025-04-30 -0.111531  0.004982 -0.040116  0.010682 -0.001248 -0.214434
2025-05-31  0.074291  0.240636  0.045027  0.018916  0.043804 -0.266211
2025-06-30  0.180263  0.169252 -0.062217 -0.043059 -0.025595  0.040656
2025-07-31  0.051379  0.125831 -0.049090 -0.036347 -0.027286 -0.200051
2025-08-31  0.035882 -0.020746  0.043663  0.108022  0.043306  0.241665
2025-09-30 -0.094063  0.071251 -0.021587 -0.053495  0.032549  0.121369
2025-10-31 -0.073713  0.085272 -0.014504 -0.003812 -0.037963 -0.010831
2025-11-30  0.000619 -0.125883 -0.014697 -0.001295  0.090239 -0.034518
2025-12-31 -0.047182  0.059607 -0.027740 -0.051005  0.002311  0.014020

Ticker             V       WMT
Date
2025-01-31  0.087150  0.090667
2025-02-28  0.062962  0.004584
2025-03-31 -0.033774 -0.107280
2025-04-30 -0.014153  0.107757
2025-05-31  0.058745  0.017570
2025-06-30 -0.027766 -0.009522
2025-07-31 -0.026982  0.002045
2025-08-31  0.020057 -0.007894
2025-09-30 -0.029564  0.062693
2025-10-31 -0.001875 -0.018242
2025-11-30 -0.016545  0.092212
2025-12-31  0.057349  0.014823

[12 rows x 30 columns]

/var/folders/j6/2sp53bgs4612lcxv_stnsxk00000gn/T/ipykernel_60630/2249956258.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  mth_return_df = historical_data.pct_change().resample('M').agg(lambda x: (1 + x).prod() - 1)

In [7]:
#calculate historical cumulative returns of past 6 months
cumulative_returns_df = (mth_return_df + 1).rolling(window=6).apply(np.prod) - 1
print(cumulative_returns_df)

Ticker          AAPL      AMGN      AMZN       AXP        BA       CAT  \
Date
2025-01-31       NaN       NaN       NaN       NaN       NaN       NaN
2025-02-28       NaN       NaN       NaN       NaN       NaN       NaN
2025-03-31       NaN       NaN       NaN       NaN       NaN       NaN
2025-04-30       NaN       NaN       NaN       NaN       NaN       NaN
2025-05-31       NaN       NaN       NaN       NaN       NaN       NaN
2025-06-30 -0.156593  0.095160 -0.003769  0.074930  0.219119  0.088221
2025-07-31 -0.118344  0.051479 -0.015020 -0.051624  0.256741  0.189267
2025-08-31 -0.037760 -0.050162  0.078764  0.107187  0.343870  0.228667
2025-09-30  0.149116 -0.078788  0.154052  0.241792  0.265494  0.459078
2025-10-31  0.275444  0.043275  0.324260  0.360899  0.097031  0.878744
2025-11-30  0.391273  0.217109  0.137603  0.248495 -0.088366  0.665171
2025-12-31  0.333796  0.195229  0.059893  0.176504  0.042810  0.497051

Ticker           CRM      CSCO       CVX       DIS  ...       MRK      MSFT  \
Date                                                ...
2025-01-31       NaN       NaN       NaN       NaN  ...       NaN       NaN
2025-02-28       NaN       NaN       NaN       NaN  ...       NaN       NaN
2025-03-31       NaN       NaN       NaN       NaN  ...       NaN       NaN
2025-04-30       NaN       NaN       NaN       NaN  ...       NaN       NaN
2025-05-31       NaN       NaN       NaN       NaN  ...       NaN       NaN
2025-06-30 -0.172711  0.189833 -0.001147  0.123794  ... -0.186818  0.192896
2025-07-31 -0.241597  0.137734  0.040214  0.058004  ... -0.194659  0.290298
2025-08-31 -0.136950  0.091398  0.036223  0.044682  ... -0.071044  0.280775
2025-09-30 -0.112525  0.122849 -0.049966  0.165028  ... -0.046260  0.384570
2025-10-31 -0.027661  0.281721  0.186376  0.243543  ...  0.029327  0.314612
2025-11-30 -0.128358  0.235248  0.130352 -0.071873  ...  0.391534  0.072511
2025-12-31 -0.021552  0.129227  0.087545 -0.068086  ...  0.364617 -0.016515

Ticker           NKE      NVDA        PG       SHW       TRV       UNH  \
Date
2025-01-31       NaN       NaN       NaN       NaN       NaN       NaN
2025-02-28       NaN       NaN       NaN       NaN       NaN       NaN
2025-03-31       NaN       NaN       NaN       NaN       NaN       NaN
2025-04-30       NaN       NaN       NaN       NaN       NaN       NaN
2025-05-31       NaN       NaN       NaN       NaN       NaN       NaN
2025-06-30 -0.024378  0.142473 -0.028253  0.035131  0.119775 -0.374587
2025-07-31 -0.017335  0.481625 -0.081611 -0.072120  0.070163 -0.534727
2025-08-31 -0.014499  0.394557 -0.084793  0.016447  0.059017 -0.340148
2025-09-30  0.111503  0.721752 -0.086580 -0.004066  0.064447 -0.331847
2025-10-31  0.158814  0.859305 -0.062207 -0.018349  0.025317 -0.158675
2025-11-30  0.079347  0.310014 -0.115802 -0.037822  0.070929  0.106973
2025-12-31 -0.128650  0.187170 -0.083296 -0.045811  0.101599  0.078639

Ticker             V       WMT
Date
2025-01-31       NaN       NaN
2025-02-28       NaN       NaN
2025-03-31       NaN       NaN
2025-04-30       NaN       NaN
2025-05-31       NaN       NaN
2025-06-30  0.133073  0.092062
2025-07-31  0.014120  0.003327
2025-08-31 -0.026814 -0.009136
2025-09-30 -0.022574  0.179525
2025-10-31 -0.010401  0.045363
2025-11-30 -0.080774  0.122043
2025-12-31 -0.000299  0.149622

[12 rows x 30 columns]

In [ ]:
# 6-Month Cumulative Returns at the End of the Measurement Period
import datetime as dt
end_of_measurement_period = dt.datetime(2025, 10, 31)
formation_period =  dt.date(2025, 11, 30)

end_of_measurement_period_return_df = cumulative_returns_df.loc[end_of_measurement_period]
end_of_measurement_period_return_df = end_of_measurement_period_return_df.reset_index()
end_of_measurement_period_return_df.head()

  Ticker  2025-10-31 00:00:00
0   AAPL             0.275444
1   AMGN             0.043275
2   AMZN             0.324260
3    AXP             0.360899
4     BA             0.097031

In [12]:
#highest momentum stock at the end of the measurement period
highest_momentum_stock = end_of_measurement_period_return_df.loc[end_of_measurement_period_return_df.iloc[:,1].idxmax()]
highest_momentum_stock.head()

Ticker                      CAT
2025-10-31 00:00:00    0.878744
Name: 5, dtype: object

In [13]:
# Display the highest momentum stock at the end of the measurement period in negative direction
lowest_momentum_stock = end_of_measurement_period_return_df.loc[end_of_measurement_period_return_df.iloc[:,1].idxmin()]
lowest_momentum_stock.head()

Ticker                      UNH
2025-10-31 00:00:00   -0.158675
Name: 27, dtype: object

In [14]:
#using pd.qcut to categorize stocks into quantiles based on their momentum
end_of_measurement_period_return_df['rank'] = pd.qcut(end_of_measurement_period_return_df.iloc[:,1], q=5, labels=False)
end_of_measurement_period_return_df.head()

  Ticker  2025-10-31 00:00:00  rank
0   AAPL             0.275444     3
1   AMGN             0.043275     1
2   AMZN             0.324260     4
3    AXP             0.360899     4
4     BA             0.097031     2

In [42]:
#obtain stocks for long
long_stocks = end_of_measurement_period_return_df[end_of_measurement_period_return_df['rank'] == 
                                                  end_of_measurement_period_return_df['rank'].max()].values
long_stocks = long_stocks[:, 0]
long_stocks

array(['AMZN', 'AXP', 'CAT', 'GOOGL', 'GS', 'NVDA'], dtype=object)

In [43]:
#obtain stocks for short
short_stocks = end_of_measurement_period_return_df[end_of_measurement_period_return_df['rank'] == 
                                                   end_of_measurement_period_return_df['rank'].min()].values
short_stocks = short_stocks[:, 0]
short_stocks

array(['CRM', 'KO', 'MCD', 'PG', 'SHW', 'UNH'], dtype=object)

In [45]:
from dateutil.relativedelta import relativedelta
december_end = pd.Timestamp(formation_period) + pd.offsets.MonthEnd(1)
long_return_df = mth_return_df.loc[december_end, long_stocks]
#long_return_df = mth_return_df.loc[formation_period + relativedelta(months=1), mth_return_df.columns.isin(long_stocks)]
long_return_df

Ticker
AMZN    -0.002959
AXP      0.022230
CAT      0.002831
GOOGL   -0.019129
GS       0.075982
NVDA     0.059607
Name: 2025-12-31 00:00:00, dtype: float64

In [47]:
#short stocks return 
short_return_df = mth_return_df.loc[december_end, short_stocks]
short_return_df

Ticker
CRM    0.155328
KO    -0.034981
MCD   -0.006227
PG    -0.027740
SHW   -0.051005
UNH    0.014020
Name: 2025-12-31 00:00:00, dtype: float64

In [ ]:
#calculate monthly portfolio return
total_return_df = long_return_df.mean() - short_return_df.mean()
np.round(total_return_df * 100, 2)

np.float64(1.49)

In [55]:
#compare with Buy and Hold strategy for the Index DJI
df_dji = yf.download('^DJI', start=start_date, end=end_date,multi_level_index=False)

buy_n_hold_df = df_dji['Close'].pct_change().resample('M').agg(lambda x: (1 + x).prod() - 1)
buy_n_hold_df

[*********************100%***********************]  1 of 1 completed
/var/folders/j6/2sp53bgs4612lcxv_stnsxk00000gn/T/ipykernel_60630/4085773526.py:4: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  buy_n_hold_df = df_dji['Close'].pct_change().resample('M').agg(lambda x: (1 + x).prod() - 1)

Date
2025-01-31    0.050773
2025-02-28   -0.015799
2025-03-31   -0.041951
2025-04-30   -0.031723
2025-05-31    0.039359
2025-06-30    0.043168
2025-07-31    0.000821
2025-08-31    0.032039
2025-09-30    0.018729
2025-10-31    0.025108
2025-11-30    0.003228
2025-12-31    0.013635
Freq: ME, Name: Close, dtype: float64

In [58]:
#monthly return for evaluation
np.round(buy_n_hold_df.loc[december_end,] * 100, 2)

np.float64(1.36)